common/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing')

]

pets/urls.py
from django.urls import path

from pets import views

urlpatterns = [
    path('', views.list_pets, name='pets'),
    path('details/<int:pk>/', views.show_pet_details, name='details'),
    path('like/<int:pk>/', views.like_pet, name='like pet'),
]

petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('pets/', include('pets.urls')),
]

common/models.py
from django.db import models

# Create your models here.

pets/models.py
from django.db import models

# Create your models here.

from django.db import models


class Pet(models.Model):
    DOG = 'dog'
    CAT = 'cat'
    PARROT = 'parrot'
    UNKNOWN = 'unknown'

    PET_TYPES = (
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        (PARROT, 'Parrot'),
        (UNKNOWN, 'Unknown'),
    )

    type = models.CharField(max_length=7, choices=PET_TYPES, default=UNKNOWN)
    name = models.CharField(max_length=6, blank=False)
    age = models.IntegerField(blank=False)
    description = models.TextField(blank=False)
    image_url = models.URLField(blank=False)

    def __str__(self):
        return f'{self.id}; {self.name}; {self.age}'


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    test = models.CharField(max_length=2, default=0)

common/views.py
from django.shortcuts import render


# Create your views here.
def landing_page(request):
    return render(request, 'landing_page.html')

pets/views.py
from django.shortcuts import render, redirect

from pets.models import Pet, Like


def list_pets(request):
    context = {
        'pets': Pet.objects.all(),
    }

    return render(request, 'pets/pets_list.html', context)


def show_pet_details(request, pk):
    context = {
        'pet': Pet.objects.get(pk=pk),
    }

    return render(request, 'pets/pet_details.html', context)


def like_pet(request, pk):
    pet = Pet.objects.get(pk=pk)
    like = Like(test=str(pk))
    like.pet = pet
    like.save()
    return redirect('pet details', pk)

templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <a class="nav-link" href="#">Home</a>
            <li class="nav-item">
                <a class="nav-link" href="#">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Sign Up</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">
                    <div class="col-lg-6">
                        <p class="lead">Already have an account? <br><a href="#" class="btn btn-lg btn-secondary">sign
                            in</a></p>
                    </div>
                    <div class="col-lg-6">
                        <p class="lead"> Do not have an account? <br>
                            <a href="#" class="btn btn-lg btn-secondary">sign up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</body>
</html>

templates/pets/pet_detail.html
{% extends 'shared/site.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/details-pet.css' %}">
{% endblock %}

{% block site_content %}
    <div class="pet-image">
        <img src="{{ pet.image_url }}" alt="image of {{ pet.name }}"/>
    </div>
    <div class="pet-info">
        <ul class="list-pet-details list-horizontal">
            <li class="list-item">
                <span class="underline"> Type:</span> {{ pet.type }}
            </li>
            <li class="list-item">
                <span class="underline"> Name:</span> {{ pet.name }}
            </li>
            <li class="list-item">
                <span class="underline"> Age:</span> {{ pet.age }}
            </li>
        </ul>
        <p>
            Description: {{ pet.description }}
        </p>
        <div class="pet-buttons">
            {#            <a class="button button-blue" href="{% url 'like pet' pet.id %}">Like</a>#}
            <a href="{% url 'like pet' pet.id %}">
                <i class="far fa-heart"></i>
            </a>
        </div>
        Likes: {{ pet.like_set.count }}
    </div>
{% endblock %}

templates/pets/pets_list.html
{% extends 'shared/site.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/list-pets.css' %}">
{% endblock %}

{% block site_content %}
    <h1>All pets</h1>
    <ul class="list-horizontal list-pets">
        {% for pet in pets %}
            <li class="list-item">
                <img src="{{ pet.image_url }}" alt="image of {{ pet.name }}">
                <div class="pet-details">
                    <p class="pet-info">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</p>
                    <p class="pet-description">{{ pet.description }}</p>
                    <div class="pet-buttons">
                        <a class="button button-blue" href="{% url 'pet details' pet.id %}">
                            {{ pet.name }}
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}